apiVersion: v1
kind: Service
metadata:
  namespace: cloud
  labels:
    app: user-server
  name: user-server
spec:
  ports:
  - name: tcp
    port: 9097
    protocol: TCP
    targetPort: 9097
  selector:
    app: user-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloud
  name: user-server
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template: 
    metadata:
      namespace: cloud
      labels:
        app: user-server
        version: v1
    spec:    
      containers:
      - name: user-server
        image: 11060/user-server:20210724125932
        resources:
          limits:
            memory: 536Mi
          requests:
            memory: 512Mi
        ports:
        - containerPort: 9097
        volumeMounts:
        - name: server-log
          mountPath: /opt/logs/user-server
        livenessProbe:
          tcpSocket:
            port: 9097
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10          
        readinessProbe:
          tcpSocket:
            port: 9097
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          failureThreshold: 5
          tcpSocket:
            port: 9097
          periodSeconds: 40
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccountName: cloud-account
      volumes:
      - name: server-log
        emptyDir: {}
