server:
  port: 5000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  security:
    user:
      name: cloud
      password: cloud@monitor
  boot:
    admin:
      ui:
        title: Microservices Monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://aAuHAd:aAuHAd@eureka-server:18761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 15
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15